name: Update from S3
on:
    schedule:
        - cron: 0 5 * * *
    workflow_dispatch: null
jobs:
    update-s3:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - name: Download file from S3
              run: |
                  # Ajusta la ruta de tu bucket y el path local según tu proyecto
                  aws s3 cp s3://TU_BUCKET/ruta/al/archivo ./src/data/archivo.txt
            - name: Commit changes
              run: |
                  git config user.name "CarlosVF22"
                  git config user.email "cevasquezf22@gmail.com"

                  # Verificar si hubo cambios
                  if [[ -n $(git status --porcelain) ]]; then
                    git add .
                    git commit -m "Update file(s) from S3"
                    git push
                  else
                    echo "No hay cambios que commitear."
